// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package text_data_client is a generated GoMock package.
package text_data_client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockstorageTextDataClient is a mock of storageTextDataClient interface.
type MockstorageTextDataClient struct {
	ctrl     *gomock.Controller
	recorder *MockstorageTextDataClientMockRecorder
}

// MockstorageTextDataClientMockRecorder is the mock recorder for MockstorageTextDataClient.
type MockstorageTextDataClientMockRecorder struct {
	mock *MockstorageTextDataClient
}

// NewMockstorageTextDataClient creates a new mock instance.
func NewMockstorageTextDataClient(ctrl *gomock.Controller) *MockstorageTextDataClient {
	mock := &MockstorageTextDataClient{ctrl: ctrl}
	mock.recorder = &MockstorageTextDataClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstorageTextDataClient) EXPECT() *MockstorageTextDataClientMockRecorder {
	return m.recorder
}

// GetIDTaskText mocks base method.
func (m *MockstorageTextDataClient) GetIDTaskText(ctx context.Context, tableName string, userID int, task string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTaskText", ctx, tableName, userID, task)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDTaskText indicates an expected call of GetIDTaskText.
func (mr *MockstorageTextDataClientMockRecorder) GetIDTaskText(ctx, tableName, userID, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTaskText", reflect.TypeOf((*MockstorageTextDataClient)(nil).GetIDTaskText), ctx, tableName, userID, task)
}

// GetUserIDWithToken mocks base method.
func (m *MockstorageTextDataClient) GetUserIDWithToken(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDWithToken", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDWithToken indicates an expected call of GetUserIDWithToken.
func (mr *MockstorageTextDataClientMockRecorder) GetUserIDWithToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDWithToken", reflect.TypeOf((*MockstorageTextDataClient)(nil).GetUserIDWithToken), ctx, token)
}

// SaveSync mocks base method.
func (m *MockstorageTextDataClient) SaveSync(ctx context.Context, tableName string, userID, taskID int, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSync", ctx, tableName, userID, taskID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSync indicates an expected call of SaveSync.
func (mr *MockstorageTextDataClientMockRecorder) SaveSync(ctx, tableName, userID, taskID, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSync", reflect.TypeOf((*MockstorageTextDataClient)(nil).SaveSync), ctx, tableName, userID, taskID, action)
}

// SaveTextDataInDatabase mocks base method.
func (m *MockstorageTextDataClient) SaveTextDataInDatabase(ctx context.Context, userID int, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveTextDataInDatabase", ctx, userID, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveTextDataInDatabase indicates an expected call of SaveTextDataInDatabase.
func (mr *MockstorageTextDataClientMockRecorder) SaveTextDataInDatabase(ctx, userID, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveTextDataInDatabase", reflect.TypeOf((*MockstorageTextDataClient)(nil).SaveTextDataInDatabase), ctx, userID, data)
}
