// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package cards_client is a generated GoMock package.
package cards_client

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockstorageClient is a mock of storageClient interface.
type MockstorageClient struct {
	ctrl     *gomock.Controller
	recorder *MockstorageClientMockRecorder
}

// MockstorageClientMockRecorder is the mock recorder for MockstorageClient.
type MockstorageClientMockRecorder struct {
	mock *MockstorageClient
}

// NewMockstorageClient creates a new mock instance.
func NewMockstorageClient(ctrl *gomock.Controller) *MockstorageClient {
	mock := &MockstorageClient{ctrl: ctrl}
	mock.recorder = &MockstorageClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstorageClient) EXPECT() *MockstorageClientMockRecorder {
	return m.recorder
}

// GetIDTaskCards mocks base method.
func (m *MockstorageClient) GetIDTaskCards(ctx context.Context, tableName string, userID int, task string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTaskCards", ctx, tableName, userID, task)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDTaskCards indicates an expected call of GetIDTaskCards.
func (mr *MockstorageClientMockRecorder) GetIDTaskCards(ctx, tableName, userID, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTaskCards", reflect.TypeOf((*MockstorageClient)(nil).GetIDTaskCards), ctx, tableName, userID, task)
}

// GetUserIDWithToken mocks base method.
func (m *MockstorageClient) GetUserIDWithToken(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDWithToken", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDWithToken indicates an expected call of GetUserIDWithToken.
func (mr *MockstorageClientMockRecorder) GetUserIDWithToken(ctx, token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDWithToken", reflect.TypeOf((*MockstorageClient)(nil).GetUserIDWithToken), ctx, token)
}

// SaveCardsInDatabase mocks base method.
func (m *MockstorageClient) SaveCardsInDatabase(ctx context.Context, userID int, card string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveCardsInDatabase", ctx, userID, card)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveCardsInDatabase indicates an expected call of SaveCardsInDatabase.
func (mr *MockstorageClientMockRecorder) SaveCardsInDatabase(ctx, userID, card interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveCardsInDatabase", reflect.TypeOf((*MockstorageClient)(nil).SaveCardsInDatabase), ctx, userID, card)
}

// SaveSync mocks base method.
func (m *MockstorageClient) SaveSync(ctx context.Context, tableName string, userID, taskID int, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveSync", ctx, tableName, userID, taskID, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveSync indicates an expected call of SaveSync.
func (mr *MockstorageClientMockRecorder) SaveSync(ctx, tableName, userID, taskID, action interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveSync", reflect.TypeOf((*MockstorageClient)(nil).SaveSync), ctx, tableName, userID, taskID, action)
}
